### ISSUE TITLE
Add GM_* variables as needed

### ISSUE THREAD

**Issue by j-f1** [j-f1/coal#2]
Currently, coal doesn’t add `GM_`* variables to the scope, because it doesn’t use a real userscript environment. This causes FIRE to fail to load.

/cc @Charcoal-SE/userscripters

**Comment by Cerbrus** [comment]
I'm working on some code to parse the metadata from the raw script.

**Comment by j-f1** [comment]
@Cerbrus [this npm package](https://github.com/pd4d10/userscript-meta) might help you. You can just `npm install --save` it and `require()` it in the `ui/` scripts.

**Comment by Cerbrus** [comment]
@j-f1 I've got the parsing figured out already (and my output is the same as Greasemonkey). I've only got to figure out how to make sure the GM_info variable is scoped correctly, when I load the userscript...

**Comment by Cerbrus** [comment]
@j-f1: In theory, this should work. However, somehow I can't get a `console.log` to work from inside `$.get(scriptUrl, function(data) {`

FIRE is updated to be able to read the data from this parser, but I didn't want to dump in in there without enough testing, which I can't do right now, 'cause there's a horse waiting for me ;-)

If you have the time, please take a look... 

    function getUserScripts (...names) {
      return $.get(
        'https://api.github.com/repos/Charcoal-SE/Userscripts/commits/master',
        ({ sha }) => names.map(name => {
          let scriptUrl = `https://cdn.rawgit.com/Charcoal-SE/Userscripts/${sha}/${name}.user.js`;
          parseMetaData(scriptUrl, $.getScript(scriptUrl));
        })
      )
    }

    function parseMetaData (scriptUrl, callback) {
      $.get(scriptUrl, function(data) {
        let metaData = data.split('\/\/ ==\/UserScript==')[0];
        metaData = metaData.split('\/\/ @');
        metaData.shift();

        let script = {excludes: [], includes: [], matches: []};

        metaData.forEach(row => {
          let split = row.trim().split(/ (.+)/);
          let key = split[0];
          let value = split[1].trim();

          if(key === "exclude")
            script.excludes.push(value);
          else if(key === "include")
            script.includes.push(value);
          else if(key === "match")
            script.matches.push(value);
          else
            script[key] = value;
        });   

        window.GM_info = { };
        GM_info[script.name] = script; // A userscript will have to use `var cachedInfo = GM_info.script || GM_info["userscript name"];`
        callback && callback(scriptUrl);
      });

    }
    
    getUserScripts(
      'fire/fire'
    );

**Comment by j-f1** [comment]
@Cerbrus When you get a chance, could you push the files to your fork and open a pull request so we can work on this together?
